# Generated by Django 4.2.1 on 2023-06-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
