# Generated by Django 4.2.1 on 2023-06-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_merge_20230604_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
